spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EasyShops
    username: postgres
    password: your_db_password
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
  async:
    request-timeout: 3600000
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: your_email@yahoo.com
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false

api:
  prefix: api/v1

auth:
  token:
    expirationInMils: 604800000 # 7 days
    jwtSecret: your_jwt_secret